-- MySQL Script generated by MySQL Workbench
-- Tue May  3 11:06:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_janela_viva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_janela_viva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_janela_viva` DEFAULT CHARACTER SET utf8 ;
USE `db_janela_viva` ;

-- -----------------------------------------------------
-- Table `db_janela_viva`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_janela_viva`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `habilidades` VARCHAR(255) NULL,
  `avaliacao` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_janela_viva`.`tb_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_janela_viva`.`tb_eventos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(2000) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `data` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_janela_viva`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_janela_viva`.`tb_postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(1000) NOT NULL,
  `curtidas` INT NULL,
  `tb_usuarios_id` BIGINT NOT NULL,
  `tb_eventos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_eventos_tb_usuarios_idx` (`tb_usuarios_id` ASC) VISIBLE,
  INDEX `fk_tb_eventos_tb_postagens1_idx` (`tb_eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_eventos_tb_usuarios`
    FOREIGN KEY (`tb_usuarios_id`)
    REFERENCES `db_janela_viva`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_eventos_tb_postagens1`
    FOREIGN KEY (`tb_eventos_id`)
    REFERENCES `db_janela_viva`.`tb_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
